#############################################################################
# Makefile for building: ChordBoard
# Generated by qmake (3.1) (Qt 5.11.3)
# Project:  ../ChordBoard Final/ChordBoard.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile ../ChordBoard\ Final/ChordBoard.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wno-deprecated-copy -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../ChordBoard\ Final -I. -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtMultimedia -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ChordBoard1.0.0
DISTDIR = /home/pi/build-ChordBoard-Desktop-Release/.tmp/ChordBoard1.0.0
LINK          = g++
LFLAGS        = -no-pie -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Multimedia -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../ChordBoard\ Final/main.cpp \
		../ChordBoard\ Final/dialog.cpp \
		../ChordBoard\ Final/mainwindow.cpp \
		../ChordBoard\ Final/pianowidget.cpp \
		../ChordBoard\ Final/instrument_select.cpp \
		../ChordBoard\ Final/Note.cpp \
		../ChordBoard\ Final/Chord.cpp \
		../ChordBoard\ Final/findChord.cpp \
		../ChordBoard\ Final/makeSong.cpp \
		../ChordBoard\ Final/drum_widget.cpp \
		../ChordBoard\ Final/trumpet_widget.cpp \
		../ChordBoard\ Final/drum.cpp \
		../ChordBoard\ Final/hintwindow.cpp \
		../ChordBoard\ Final/widget.cpp moc_dialog.cpp \
		moc_mainwindow.cpp \
		moc_pianowidget.cpp \
		moc_instrument_select.cpp \
		moc_drum_widget.cpp \
		moc_trumpet_widget.cpp \
		moc_hintwindow.cpp \
		moc_widget.cpp
OBJECTS       = qrc_assets.o \
		main.o \
		dialog.o \
		mainwindow.o \
		pianowidget.o \
		instrument_select.o \
		Note.o \
		Chord.o \
		findChord.o \
		makeSong.o \
		drum_widget.o \
		trumpet_widget.o \
		drum.o \
		hintwindow.o \
		widget.o \
		moc_dialog.o \
		moc_mainwindow.o \
		moc_pianowidget.o \
		moc_instrument_select.o \
		moc_drum_widget.o \
		moc_trumpet_widget.o \
		moc_hintwindow.o \
		moc_widget.o
DIST          = /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		../ChordBoard Final/ChordBoard.pro ../ChordBoard\ Final/dialog.h \
		../ChordBoard\ Final/mainwindow.h \
		../ChordBoard\ Final/pianowidget.h \
		../ChordBoard\ Final/instrument_select.h \
		../ChordBoard\ Final/Note.h \
		../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/findChord.h \
		../ChordBoard\ Final/makeSong.h \
		../ChordBoard\ Final/drum_widget.h \
		../ChordBoard\ Final/trumpet_widget.h \
		../ChordBoard\ Final/drum.h \
		../ChordBoard\ Final/hintwindow.h \
		../ChordBoard\ Final/widget.h ../ChordBoard\ Final/main.cpp \
		../ChordBoard\ Final/dialog.cpp \
		../ChordBoard\ Final/mainwindow.cpp \
		../ChordBoard\ Final/pianowidget.cpp \
		../ChordBoard\ Final/instrument_select.cpp \
		../ChordBoard\ Final/Note.cpp \
		../ChordBoard\ Final/Chord.cpp \
		../ChordBoard\ Final/findChord.cpp \
		../ChordBoard\ Final/makeSong.cpp \
		../ChordBoard\ Final/drum_widget.cpp \
		../ChordBoard\ Final/trumpet_widget.cpp \
		../ChordBoard\ Final/drum.cpp \
		../ChordBoard\ Final/hintwindow.cpp \
		../ChordBoard\ Final/widget.cpp
QMAKE_TARGET  = ChordBoard
DESTDIR       = 
TARGET        = ChordBoard


first: all
####### Build rules

$(TARGET): ui_dialog.h ui_mainwindow.h ui_pianowidget.h ui_instrument_select.h ui_drum_widget.h ui_trumpet_widget.h ui_hintwindow.h ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../ChordBoard\ Final/ChordBoard.pro /usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		../ChordBoard\ Final/ChordBoard.pro \
		../ChordBoard\ Final/assets.qrc \
		/usr/lib/i386-linux-gnu/libQt5Multimedia.prl \
		/usr/lib/i386-linux-gnu/libQt5Widgets.prl \
		/usr/lib/i386-linux-gnu/libQt5Gui.prl \
		/usr/lib/i386-linux-gnu/libQt5Network.prl \
		/usr/lib/i386-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile ../ChordBoard\ Final/ChordBoard.pro -spec linux-g++
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf:
../ChordBoard\ Final/ChordBoard.pro:
../ChordBoard\ Final/assets.qrc:
/usr/lib/i386-linux-gnu/libQt5Multimedia.prl:
/usr/lib/i386-linux-gnu/libQt5Widgets.prl:
/usr/lib/i386-linux-gnu/libQt5Gui.prl:
/usr/lib/i386-linux-gnu/libQt5Network.prl:
/usr/lib/i386-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../ChordBoard\ Final/ChordBoard.pro -spec linux-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../ChordBoard\ Final/assets.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/i386-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../ChordBoard\ Final/dialog.h ../ChordBoard\ Final/mainwindow.h ../ChordBoard\ Final/pianowidget.h ../ChordBoard\ Final/instrument_select.h ../ChordBoard\ Final/Note.h ../ChordBoard\ Final/Chord.h ../ChordBoard\ Final/findChord.h ../ChordBoard\ Final/makeSong.h ../ChordBoard\ Final/drum_widget.h ../ChordBoard\ Final/trumpet_widget.h ../ChordBoard\ Final/drum.h ../ChordBoard\ Final/hintwindow.h ../ChordBoard\ Final/widget.h $(DISTDIR)/
	$(COPY_FILE) --parents ../ChordBoard\ Final/main.cpp ../ChordBoard\ Final/dialog.cpp ../ChordBoard\ Final/mainwindow.cpp ../ChordBoard\ Final/pianowidget.cpp ../ChordBoard\ Final/instrument_select.cpp ../ChordBoard\ Final/Note.cpp ../ChordBoard\ Final/Chord.cpp ../ChordBoard\ Final/findChord.cpp ../ChordBoard\ Final/makeSong.cpp ../ChordBoard\ Final/drum_widget.cpp ../ChordBoard\ Final/trumpet_widget.cpp ../ChordBoard\ Final/drum.cpp ../ChordBoard\ Final/hintwindow.cpp ../ChordBoard\ Final/widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../ChordBoard\ Final/dialog.ui ../ChordBoard\ Final/mainwindow.ui ../ChordBoard\ Final/pianowidget.ui ../ChordBoard\ Final/instrument_select.ui ../ChordBoard\ Final/drum_widget.ui ../ChordBoard\ Final/trumpet_widget.ui ../ChordBoard\ Final/hintwindow.ui ../ChordBoard\ Final/widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_assets.o
compiler_rcc_clean:
	-$(DEL_FILE) qrc_assets.cpp qrc_assets.tmp.o
qrc_assets.o: ../ChordBoard\ Final/assets.qrc \
		/usr/lib/qt5/bin/rcc
	/usr/lib/qt5/bin/rcc -name assets ../ChordBoard\ Final/assets.qrc -pass 1 -o ./qrc_assets.cpp 
	 g++ $(CXXFLAGS) -c ./qrc_assets.cpp -o ./qrc_assets.tmp.o 
	 /usr/lib/qt5/bin/rcc -name assets ../ChordBoard\ Final/assets.qrc -pass 2 -temp ./qrc_assets.tmp.o -o qrc_assets.o

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/i386-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -Wno-deprecated-copy -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/i386-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_dialog.cpp moc_mainwindow.cpp moc_pianowidget.cpp moc_instrument_select.cpp moc_drum_widget.cpp moc_trumpet_widget.cpp moc_hintwindow.cpp moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_mainwindow.cpp moc_pianowidget.cpp moc_instrument_select.cpp moc_drum_widget.cpp moc_trumpet_widget.cpp moc_hintwindow.cpp moc_widget.cpp
moc_dialog.cpp: ../ChordBoard\ Final/dialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/build-ChordBoard-Desktop-Release/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/pi/ChordBoard Final' -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include ../ChordBoard\ Final/dialog.h -o moc_dialog.cpp

moc_mainwindow.cpp: ../ChordBoard\ Final/dialog.h \
		../ChordBoard\ Final/pianowidget.h \
		../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h \
		../ChordBoard\ Final/findChord.h \
		../ChordBoard\ Final/makeSong.h \
		../ChordBoard\ Final/drum_widget.h \
		../ChordBoard\ Final/drum.h \
		../ChordBoard\ Final/hintwindow.h \
		../ChordBoard\ Final/trumpet_widget.h \
		../ChordBoard\ Final/instrument_select.h \
		../ChordBoard\ Final/widget.h \
		../ChordBoard\ Final/mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/build-ChordBoard-Desktop-Release/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/pi/ChordBoard Final' -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include ../ChordBoard\ Final/mainwindow.h -o moc_mainwindow.cpp

moc_pianowidget.cpp: ../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h \
		../ChordBoard\ Final/findChord.h \
		../ChordBoard\ Final/makeSong.h \
		../ChordBoard\ Final/pianowidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/build-ChordBoard-Desktop-Release/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/pi/ChordBoard Final' -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include ../ChordBoard\ Final/pianowidget.h -o moc_pianowidget.cpp

moc_instrument_select.cpp: ../ChordBoard\ Final/instrument_select.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/build-ChordBoard-Desktop-Release/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/pi/ChordBoard Final' -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include ../ChordBoard\ Final/instrument_select.h -o moc_instrument_select.cpp

moc_drum_widget.cpp: ../ChordBoard\ Final/drum.h \
		../ChordBoard\ Final/hintwindow.h \
		../ChordBoard\ Final/drum_widget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/build-ChordBoard-Desktop-Release/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/pi/ChordBoard Final' -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include ../ChordBoard\ Final/drum_widget.h -o moc_drum_widget.cpp

moc_trumpet_widget.cpp: ../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h \
		../ChordBoard\ Final/findChord.h \
		../ChordBoard\ Final/trumpet_widget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/build-ChordBoard-Desktop-Release/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/pi/ChordBoard Final' -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include ../ChordBoard\ Final/trumpet_widget.h -o moc_trumpet_widget.cpp

moc_hintwindow.cpp: ../ChordBoard\ Final/hintwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/build-ChordBoard-Desktop-Release/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/pi/ChordBoard Final' -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include ../ChordBoard\ Final/hintwindow.h -o moc_hintwindow.cpp

moc_widget.cpp: ../ChordBoard\ Final/makeSong.h \
		../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h \
		../ChordBoard\ Final/findChord.h \
		../ChordBoard\ Final/widget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/pi/build-ChordBoard-Desktop-Release/moc_predefs.h -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I'/home/pi/ChordBoard Final' -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtMultimedia -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/8 -I/usr/include/i386-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/i686-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/8/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include ../ChordBoard\ Final/widget.h -o moc_widget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h ui_mainwindow.h ui_pianowidget.h ui_instrument_select.h ui_drum_widget.h ui_trumpet_widget.h ui_hintwindow.h ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h ui_mainwindow.h ui_pianowidget.h ui_instrument_select.h ui_drum_widget.h ui_trumpet_widget.h ui_hintwindow.h ui_widget.h
ui_dialog.h: ../ChordBoard\ Final/dialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../ChordBoard\ Final/dialog.ui -o ui_dialog.h

ui_mainwindow.h: ../ChordBoard\ Final/mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../ChordBoard\ Final/mainwindow.ui -o ui_mainwindow.h

ui_pianowidget.h: ../ChordBoard\ Final/pianowidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../ChordBoard\ Final/pianowidget.ui -o ui_pianowidget.h

ui_instrument_select.h: ../ChordBoard\ Final/instrument_select.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../ChordBoard\ Final/instrument_select.ui -o ui_instrument_select.h

ui_drum_widget.h: ../ChordBoard\ Final/drum_widget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../ChordBoard\ Final/drum_widget.ui -o ui_drum_widget.h

ui_trumpet_widget.h: ../ChordBoard\ Final/trumpet_widget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../ChordBoard\ Final/trumpet_widget.ui -o ui_trumpet_widget.h

ui_hintwindow.h: ../ChordBoard\ Final/hintwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../ChordBoard\ Final/hintwindow.ui -o ui_hintwindow.h

ui_widget.h: ../ChordBoard\ Final/widget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic ../ChordBoard\ Final/widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../ChordBoard\ Final/main.cpp ../ChordBoard\ Final/mainwindow.h \
		../ChordBoard\ Final/dialog.h \
		../ChordBoard\ Final/pianowidget.h \
		../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h \
		../ChordBoard\ Final/findChord.h \
		../ChordBoard\ Final/makeSong.h \
		../ChordBoard\ Final/drum_widget.h \
		../ChordBoard\ Final/drum.h \
		../ChordBoard\ Final/hintwindow.h \
		../ChordBoard\ Final/trumpet_widget.h \
		../ChordBoard\ Final/instrument_select.h \
		../ChordBoard\ Final/widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../ChordBoard\ Final/main.cpp

dialog.o: ../ChordBoard\ Final/dialog.cpp ../ChordBoard\ Final/dialog.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o ../ChordBoard\ Final/dialog.cpp

mainwindow.o: ../ChordBoard\ Final/mainwindow.cpp ../ChordBoard\ Final/mainwindow.h \
		../ChordBoard\ Final/dialog.h \
		../ChordBoard\ Final/pianowidget.h \
		../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h \
		../ChordBoard\ Final/findChord.h \
		../ChordBoard\ Final/makeSong.h \
		../ChordBoard\ Final/drum_widget.h \
		../ChordBoard\ Final/drum.h \
		../ChordBoard\ Final/hintwindow.h \
		../ChordBoard\ Final/trumpet_widget.h \
		../ChordBoard\ Final/instrument_select.h \
		../ChordBoard\ Final/widget.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../ChordBoard\ Final/mainwindow.cpp

pianowidget.o: ../ChordBoard\ Final/pianowidget.cpp ../ChordBoard\ Final/pianowidget.h \
		../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h \
		../ChordBoard\ Final/findChord.h \
		../ChordBoard\ Final/makeSong.h \
		ui_pianowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pianowidget.o ../ChordBoard\ Final/pianowidget.cpp

instrument_select.o: ../ChordBoard\ Final/instrument_select.cpp ../ChordBoard\ Final/instrument_select.h \
		ui_instrument_select.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o instrument_select.o ../ChordBoard\ Final/instrument_select.cpp

Note.o: ../ChordBoard\ Final/Note.cpp ../ChordBoard\ Final/Note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Note.o ../ChordBoard\ Final/Note.cpp

Chord.o: ../ChordBoard\ Final/Chord.cpp ../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Chord.o ../ChordBoard\ Final/Chord.cpp

findChord.o: ../ChordBoard\ Final/findChord.cpp ../ChordBoard\ Final/findChord.h \
		../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o findChord.o ../ChordBoard\ Final/findChord.cpp

makeSong.o: ../ChordBoard\ Final/makeSong.cpp ../ChordBoard\ Final/makeSong.h \
		../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o makeSong.o ../ChordBoard\ Final/makeSong.cpp

drum_widget.o: ../ChordBoard\ Final/drum_widget.cpp ../ChordBoard\ Final/drum_widget.h \
		../ChordBoard\ Final/drum.h \
		../ChordBoard\ Final/hintwindow.h \
		ui_drum_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drum_widget.o ../ChordBoard\ Final/drum_widget.cpp

trumpet_widget.o: ../ChordBoard\ Final/trumpet_widget.cpp ../ChordBoard\ Final/trumpet_widget.h \
		../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h \
		../ChordBoard\ Final/findChord.h \
		ui_trumpet_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trumpet_widget.o ../ChordBoard\ Final/trumpet_widget.cpp

drum.o: ../ChordBoard\ Final/drum.cpp ../ChordBoard\ Final/drum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drum.o ../ChordBoard\ Final/drum.cpp

hintwindow.o: ../ChordBoard\ Final/hintwindow.cpp ../ChordBoard\ Final/hintwindow.h \
		ui_hintwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hintwindow.o ../ChordBoard\ Final/hintwindow.cpp

widget.o: ../ChordBoard\ Final/widget.cpp ../ChordBoard\ Final/widget.h \
		../ChordBoard\ Final/makeSong.h \
		../ChordBoard\ Final/Chord.h \
		../ChordBoard\ Final/Note.h \
		../ChordBoard\ Final/findChord.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o ../ChordBoard\ Final/widget.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pianowidget.o: moc_pianowidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pianowidget.o moc_pianowidget.cpp

moc_instrument_select.o: moc_instrument_select.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_instrument_select.o moc_instrument_select.cpp

moc_drum_widget.o: moc_drum_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drum_widget.o moc_drum_widget.cpp

moc_trumpet_widget.o: moc_trumpet_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_trumpet_widget.o moc_trumpet_widget.cpp

moc_hintwindow.o: moc_hintwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hintwindow.o moc_hintwindow.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ChordBoard/bin || mkdir -p $(INSTALL_ROOT)/opt/ChordBoard/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ChordBoard/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/ChordBoard/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ChordBoard/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ChordBoard/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

