#############################################################################
# Makefile for building: ChordBoard
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  ../Prog/ChordBoard.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 -o Makefile ../Prog/ChordBoard.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -Wno-deprecated-copy -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../Prog -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ChordBoard1.0.0
DISTDIR = /home/test/build-ChordBoard-Desktop-Release/.tmp/ChordBoard1.0.0
LINK          = g++
LFLAGS        = -m64 -no-pie -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Multimedia -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../Prog/main.cpp \
		../Prog/dialog.cpp \
		../Prog/mainwindow.cpp \
		../Prog/pianowidget.cpp \
		../Prog/instrument_select.cpp \
		../Prog/Note.cpp \
		../Prog/Chord.cpp \
		../Prog/findChord.cpp \
		../Prog/makeSong.cpp \
		../Prog/drum_widget.cpp \
		../Prog/trumpet_widget.cpp \
		../Prog/drum.cpp \
		../Prog/hintwindow.cpp \
		../Prog/widget.cpp moc_dialog.cpp \
		moc_mainwindow.cpp \
		moc_pianowidget.cpp \
		moc_instrument_select.cpp \
		moc_drum_widget.cpp \
		moc_trumpet_widget.cpp \
		moc_hintwindow.cpp \
		moc_widget.cpp
OBJECTS       = qrc_assets.o \
		main.o \
		dialog.o \
		mainwindow.o \
		pianowidget.o \
		instrument_select.o \
		Note.o \
		Chord.o \
		findChord.o \
		makeSong.o \
		drum_widget.o \
		trumpet_widget.o \
		drum.o \
		hintwindow.o \
		widget.o \
		moc_dialog.o \
		moc_mainwindow.o \
		moc_pianowidget.o \
		moc_instrument_select.o \
		moc_drum_widget.o \
		moc_trumpet_widget.o \
		moc_hintwindow.o \
		moc_widget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		../Prog/ChordBoard.pro ../Prog/dialog.h \
		../Prog/mainwindow.h \
		../Prog/pianowidget.h \
		../Prog/instrument_select.h \
		../Prog/Note.h \
		../Prog/Chord.h \
		../Prog/findChord.h \
		../Prog/makeSong.h \
		../Prog/drum_widget.h \
		../Prog/trumpet_widget.h \
		../Prog/drum.h \
		../Prog/hintwindow.h \
		../Prog/widget.h ../Prog/main.cpp \
		../Prog/dialog.cpp \
		../Prog/mainwindow.cpp \
		../Prog/pianowidget.cpp \
		../Prog/instrument_select.cpp \
		../Prog/Note.cpp \
		../Prog/Chord.cpp \
		../Prog/findChord.cpp \
		../Prog/makeSong.cpp \
		../Prog/drum_widget.cpp \
		../Prog/trumpet_widget.cpp \
		../Prog/drum.cpp \
		../Prog/hintwindow.cpp \
		../Prog/widget.cpp
QMAKE_TARGET  = ChordBoard
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ChordBoard


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_dialog.h ui_mainwindow.h ui_pianowidget.h ui_instrument_select.h ui_drum_widget.h ui_trumpet_widget.h ui_hintwindow.h ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../Prog/ChordBoard.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		../Prog/ChordBoard.pro \
		../Prog/assets.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Multimedia.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 -o Makefile ../Prog/ChordBoard.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
../Prog/ChordBoard.pro:
../Prog/assets.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Multimedia.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 -o Makefile ../Prog/ChordBoard.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Prog/assets.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../Prog/dialog.h ../Prog/mainwindow.h ../Prog/pianowidget.h ../Prog/instrument_select.h ../Prog/Note.h ../Prog/Chord.h ../Prog/findChord.h ../Prog/makeSong.h ../Prog/drum_widget.h ../Prog/trumpet_widget.h ../Prog/drum.h ../Prog/hintwindow.h ../Prog/widget.h $(DISTDIR)/
	$(COPY_FILE) --parents ../Prog/main.cpp ../Prog/dialog.cpp ../Prog/mainwindow.cpp ../Prog/pianowidget.cpp ../Prog/instrument_select.cpp ../Prog/Note.cpp ../Prog/Chord.cpp ../Prog/findChord.cpp ../Prog/makeSong.cpp ../Prog/drum_widget.cpp ../Prog/trumpet_widget.cpp ../Prog/drum.cpp ../Prog/hintwindow.cpp ../Prog/widget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../Prog/dialog.ui ../Prog/mainwindow.ui ../Prog/pianowidget.ui ../Prog/instrument_select.ui ../Prog/drum_widget.ui ../Prog/trumpet_widget.ui ../Prog/hintwindow.ui ../Prog/widget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_assets.o
compiler_rcc_clean:
	-$(DEL_FILE) qrc_assets.cpp qrc_assets.tmp.o
qrc_assets.o: ../Prog/assets.qrc \
		../Prog/assets/flute_F5_1_forte_normal.wav \
		../Prog/assets/flute_Gb4_1_forte_normal.wav \
		../Prog/assets/flute_Ab4_1_forte_normal.wav \
		../Prog/assets/flute_E7_1_forte_normal.wav \
		../Prog/assets/flute_Db6_1_forte_normal.wav \
		../Prog/assets/flute_F4_1_forte_normal.wav \
		../Prog/assets/flute_hint.jpg \
		../Prog/assets/flute_G6_1_forte_normal.wav \
		../Prog/assets/flute_Db5_1_forte_normal.wav \
		../Prog/assets/flute_B4_1_forte_normal.wav \
		../Prog/assets/flute_A6_1_forte_normal.wav \
		../Prog/assets/flute_G5_1_forte_normal.wav \
		../Prog/assets/flute.jpg \
		../Prog/assets/flute_Db4_1_forte_normal.wav \
		../Prog/assets/flute_F7_1_forte_normal.wav \
		../Prog/assets/flute_C5_1_forte_normal.wav \
		../Prog/assets/flute_A5_1_forte_normal.wav \
		../Prog/assets/flute_G4_1_forte_normal.wav \
		../Prog/assets/flute_Eb7_1_forte_normal.wav \
		../Prog/assets/flute_C4_1_forte_normal.wav \
		../Prog/assets/flute_B6_1_forte_normal.wav \
		../Prog/assets/flute_Eb6_1_forte_normal.wav \
		../Prog/assets/flute_D5_1_forte_normal.wav \
		../Prog/assets/flute_B5_1_forte_normal.wav \
		../Prog/assets/flute_Eb5_1_forte_normal.wav \
		../Prog/assets/flute_C7_1_forte_normal.wav \
		../Prog/assets/flute_D4_1_forte_normal.wav \
		../Prog/assets/flute_E6_1_forte_normal.wav \
		../Prog/assets/flute_Eb4_1_forte_normal.wav \
		../Prog/assets/flute_C6_1_forte_normal.wav \
		../Prog/assets/flute_Bb6_1_forte_normal.wav \
		../Prog/assets/flute_E5_1_forte_normal.wav \
		../Prog/assets/flute_Gb6_1_forte_normal.wav \
		../Prog/assets/flute_Ab6_1_forte_normal.wav \
		../Prog/assets/flute_D7_1_forte_normal.wav \
		../Prog/assets/flute_Bb5_1_forte_normal.wav \
		../Prog/assets/flute_E4_1_forte_normal.wav \
		../Prog/assets/flute_F6_1_forte_normal.wav \
		../Prog/assets/flute_Gb5_1_forte_normal.wav \
		../Prog/assets/flute_D6_1_forte_normal.wav \
		../Prog/assets/flute_A4_1_forte_normal.wav \
		../Prog/assets/flute_Ab5_1_forte_normal.wav \
		../Prog/assets/flute_Bb4_1_forte_normal.wav \
		../Prog/assets/flute_Db7_1_forte_normal.wav \
		../Prog/assets/drum_topdown_graphicx.jpg \
		../Prog/assets/snare.wav \
		../Prog/assets/floor_tom.wav \
		../Prog/assets/crash_cymbal.wav \
		../Prog/assets/closed_hihat.wav \
		../Prog/assets/Parts-of-a-drum-set.png \
		../Prog/assets/medium_tom.wav \
		../Prog/assets/open_hihat.wav \
		../Prog/assets/ride_cymbal.wav \
		../Prog/assets/another_drum.jpg \
		../Prog/assets/hi_tom.wav \
		../Prog/assets/bass_drum.wav \
		../Prog/assets/high_tom_short_reverb.wav \
		../Prog/assets/check_mark.png \
		../Prog/assets/more_drums.jpg \
		../Prog/assets/E5.wav \
		../Prog/assets/D7.wav \
		../Prog/assets/B2.wav \
		../Prog/assets/A4.wav \
		../Prog/assets/F2.wav \
		../Prog/assets/E4.wav \
		../Prog/assets/piano_scales \
		../Prog/assets/D6.wav \
		../Prog/assets/B1.wav \
		../Prog/assets/C8.wav \
		../Prog/assets/A3.wav \
		../Prog/assets/F1.wav \
		../Prog/assets/E3.wav \
		../Prog/assets/metronomeTick.wav \
		../Prog/assets/D5.wav \
		../Prog/assets/B0.wav \
		../Prog/assets/C7.wav \
		../Prog/assets/A2.wav \
		../Prog/assets/E2.wav \
		../Prog/assets/G7.wav \
		../Prog/assets/piano.webp \
		../Prog/assets/D4.wav \
		../Prog/assets/C6.wav \
		../Prog/assets/A1.wav \
		../Prog/assets/E1.wav \
		../Prog/assets/G6.wav \
		../Prog/assets/D3.wav \
		../Prog/assets/C5.wav \
		../Prog/assets/A0.wav \
		../Prog/assets/B7.wav \
		../Prog/assets/G5.wav \
		../Prog/assets/D2.wav \
		../Prog/assets/F7.wav \
		../Prog/assets/C4.wav \
		../Prog/assets/B6.wav \
		../Prog/assets/G4.wav \
		../Prog/assets/D1.wav \
		../Prog/assets/F6.wav \
		../Prog/assets/C3.wav \
		../Prog/assets/B5.wav \
		../Prog/assets/G3.wav \
		../Prog/assets/A7.wav \
		../Prog/assets/F5.wav \
		../Prog/assets/E7.wav \
		../Prog/assets/C2.wav \
		../Prog/assets/B4.wav \
		../Prog/assets/G2.wav \
		../Prog/assets/A6.wav \
		../Prog/assets/F4.wav \
		../Prog/assets/C1.wav \
		../Prog/assets/E6.wav \
		../Prog/assets/B3.wav \
		../Prog/assets/G1.wav \
		../Prog/assets/A5.wav \
		../Prog/assets/F3.wav \
		../Prog/assets/trumpet_D5.wav \
		../Prog/assets/trumpet_D5.mp3 \
		../Prog/assets/trumpet_graphic.jpg \
		../Prog/assets/trumpet_help.jpg \
		../Prog/assets/trumpet_notes \
		../Prog/assets/trumpet_C4.wav \
		../Prog/assets/trumpet_C5.wav \
		../Prog/assets/trumpet_B3.wav \
		../Prog/assets/trumpet_G3.wav \
		../Prog/assets/trumpet_G4.wav \
		../Prog/assets/trumpet_B4.wav \
		../Prog/assets/trumpet_G5.wav \
		../Prog/assets/trumpet_A3.wav \
		../Prog/assets/trumpet_A4.wav \
		../Prog/assets/trumpet_F4.wav \
		../Prog/assets/trumpet_F5.wav \
		../Prog/assets/trumpet_F5.mp3 \
		../Prog/assets/trumpet_E4.wav \
		../Prog/assets/trumpet_E5.wav \
		../Prog/assets/trumpet_D4.wav
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name assets ../Prog/assets.qrc -pass 1 -o ./qrc_assets.cpp 
	 g++ $(CXXFLAGS) -c ./qrc_assets.cpp -o ./qrc_assets.tmp.o 
	 /usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name assets ../Prog/assets.qrc -pass 2 -temp ./qrc_assets.tmp.o -o qrc_assets.o

compiler_moc_header_make_all: moc_dialog.cpp moc_mainwindow.cpp moc_pianowidget.cpp moc_instrument_select.cpp moc_drum_widget.cpp moc_trumpet_widget.cpp moc_hintwindow.cpp moc_widget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp moc_mainwindow.cpp moc_pianowidget.cpp moc_instrument_select.cpp moc_drum_widget.cpp moc_trumpet_widget.cpp moc_hintwindow.cpp moc_widget.cpp
moc_dialog.cpp: ../Prog/dialog.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/test/Prog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Prog/dialog.h -o moc_dialog.cpp

moc_mainwindow.cpp: ../Prog/dialog.h \
		../Prog/pianowidget.h \
		../Prog/Chord.h \
		../Prog/Note.h \
		../Prog/findChord.h \
		../Prog/makeSong.h \
		../Prog/drum_widget.h \
		../Prog/drum.h \
		../Prog/hintwindow.h \
		../Prog/trumpet_widget.h \
		../Prog/instrument_select.h \
		../Prog/widget.h \
		../Prog/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/test/Prog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Prog/mainwindow.h -o moc_mainwindow.cpp

moc_pianowidget.cpp: ../Prog/Chord.h \
		../Prog/Note.h \
		../Prog/findChord.h \
		../Prog/makeSong.h \
		../Prog/pianowidget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/test/Prog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Prog/pianowidget.h -o moc_pianowidget.cpp

moc_instrument_select.cpp: ../Prog/instrument_select.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/test/Prog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Prog/instrument_select.h -o moc_instrument_select.cpp

moc_drum_widget.cpp: ../Prog/drum.h \
		../Prog/hintwindow.h \
		../Prog/drum_widget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/test/Prog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Prog/drum_widget.h -o moc_drum_widget.cpp

moc_trumpet_widget.cpp: ../Prog/Chord.h \
		../Prog/Note.h \
		../Prog/findChord.h \
		../Prog/trumpet_widget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/test/Prog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Prog/trumpet_widget.h -o moc_trumpet_widget.cpp

moc_hintwindow.cpp: ../Prog/hintwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/test/Prog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Prog/hintwindow.h -o moc_hintwindow.cpp

moc_widget.cpp: ../Prog/makeSong.h \
		../Prog/Chord.h \
		../Prog/Note.h \
		../Prog/findChord.h \
		../Prog/widget.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/test/Prog -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include ../Prog/widget.h -o moc_widget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h ui_mainwindow.h ui_pianowidget.h ui_instrument_select.h ui_drum_widget.h ui_trumpet_widget.h ui_hintwindow.h ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h ui_mainwindow.h ui_pianowidget.h ui_instrument_select.h ui_drum_widget.h ui_trumpet_widget.h ui_hintwindow.h ui_widget.h
ui_dialog.h: ../Prog/dialog.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ../Prog/dialog.ui -o ui_dialog.h

ui_mainwindow.h: ../Prog/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ../Prog/mainwindow.ui -o ui_mainwindow.h

ui_pianowidget.h: ../Prog/pianowidget.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ../Prog/pianowidget.ui -o ui_pianowidget.h

ui_instrument_select.h: ../Prog/instrument_select.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ../Prog/instrument_select.ui -o ui_instrument_select.h

ui_drum_widget.h: ../Prog/drum_widget.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ../Prog/drum_widget.ui -o ui_drum_widget.h

ui_trumpet_widget.h: ../Prog/trumpet_widget.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ../Prog/trumpet_widget.ui -o ui_trumpet_widget.h

ui_hintwindow.h: ../Prog/hintwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ../Prog/hintwindow.ui -o ui_hintwindow.h

ui_widget.h: ../Prog/widget.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic ../Prog/widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../Prog/main.cpp ../Prog/mainwindow.h \
		../Prog/dialog.h \
		../Prog/pianowidget.h \
		../Prog/Chord.h \
		../Prog/Note.h \
		../Prog/findChord.h \
		../Prog/makeSong.h \
		../Prog/drum_widget.h \
		../Prog/drum.h \
		../Prog/hintwindow.h \
		../Prog/trumpet_widget.h \
		../Prog/instrument_select.h \
		../Prog/widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../Prog/main.cpp

dialog.o: ../Prog/dialog.cpp ../Prog/dialog.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o ../Prog/dialog.cpp

mainwindow.o: ../Prog/mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../Prog/mainwindow.cpp

pianowidget.o: ../Prog/pianowidget.cpp ../Prog/pianowidget.h \
		../Prog/Chord.h \
		../Prog/Note.h \
		../Prog/findChord.h \
		../Prog/makeSong.h \
		ui_pianowidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pianowidget.o ../Prog/pianowidget.cpp

instrument_select.o: ../Prog/instrument_select.cpp ../Prog/instrument_select.h \
		ui_instrument_select.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o instrument_select.o ../Prog/instrument_select.cpp

Note.o: ../Prog/Note.cpp ../Prog/Note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Note.o ../Prog/Note.cpp

Chord.o: ../Prog/Chord.cpp ../Prog/Chord.h \
		../Prog/Note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Chord.o ../Prog/Chord.cpp

findChord.o: ../Prog/findChord.cpp ../Prog/findChord.h \
		../Prog/Chord.h \
		../Prog/Note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o findChord.o ../Prog/findChord.cpp

makeSong.o: ../Prog/makeSong.cpp ../Prog/makeSong.h \
		../Prog/Chord.h \
		../Prog/Note.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o makeSong.o ../Prog/makeSong.cpp

drum_widget.o: ../Prog/drum_widget.cpp ../Prog/drum_widget.h \
		../Prog/drum.h \
		../Prog/hintwindow.h \
		ui_drum_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drum_widget.o ../Prog/drum_widget.cpp

trumpet_widget.o: ../Prog/trumpet_widget.cpp ../Prog/trumpet_widget.h \
		../Prog/Chord.h \
		../Prog/Note.h \
		../Prog/findChord.h \
		ui_trumpet_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trumpet_widget.o ../Prog/trumpet_widget.cpp

drum.o: ../Prog/drum.cpp ../Prog/drum.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drum.o ../Prog/drum.cpp

hintwindow.o: ../Prog/hintwindow.cpp ../Prog/hintwindow.h \
		ui_hintwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hintwindow.o ../Prog/hintwindow.cpp

widget.o: ../Prog/widget.cpp ../Prog/widget.h \
		../Prog/makeSong.h \
		../Prog/Chord.h \
		../Prog/Note.h \
		../Prog/findChord.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o ../Prog/widget.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pianowidget.o: moc_pianowidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pianowidget.o moc_pianowidget.cpp

moc_instrument_select.o: moc_instrument_select.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_instrument_select.o moc_instrument_select.cpp

moc_drum_widget.o: moc_drum_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drum_widget.o moc_drum_widget.cpp

moc_trumpet_widget.o: moc_trumpet_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_trumpet_widget.o moc_trumpet_widget.cpp

moc_hintwindow.o: moc_hintwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hintwindow.o moc_hintwindow.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ChordBoard/bin || mkdir -p $(INSTALL_ROOT)/opt/ChordBoard/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ChordBoard/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/ChordBoard/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ChordBoard/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ChordBoard/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

